import {
    ArrowRightLeft,
    Bell,
    Book,
    Building,
    Check,
    ChevronDown,
    ChevronRight,
    ChevronsUpDown,
    CreditCard,
    Database,
    Download,
    Eye,
    FileText,
    FileUp,
    GripVertical,
    LayoutDashboard,
    Lock,
    LogOut,
    Mail,
    MapPin,
    Menu,
    MessageSquare,
    MoreVertical,
    NotebookText,
    Pencil,
    Phone,
    Plus,
    Receipt,
    Save,
    Search,
    Send,
    Settings,
    Shield,
    Star,
    Trash2,
    User,
    UserCog,
    Users,
    X,
} from 'lucide-react';

export const Icons = {
    Dashboard: LayoutDashboard,
    Transactions: ArrowRightLeft,
    Reports: FileText,
    ChartOfAccounts: Book,
    JournalEntries: NotebookText,
    Invoices: FileText,
    Expenses: Receipt,
    Documents: FileUp,
    ClientReview: MessageSquare,
    Settings: Settings,
    Profile: User,
    Billing: CreditCard,
    Notifications: Bell,
    Logout: LogOut,
    ChevronRight: ChevronRight,
    ChevronDown: ChevronDown,
    ChevronsUpDown: ChevronsUpDown,
    UserCircle: User,
    Menu: Menu,
    Search: Search,
    Building: Building,
    Users: Users,
    Roles: UserCog,
    Shield: Shield,
    Lock: Lock,
    Database: Database,
    Edit: Pencil,
    Save: Save,
    Plus: Plus,
    Trash: Trash2,
    Mail: Mail,
    Phone: Phone,
    MapPin: MapPin,
    Check: Check,
    Close: X,
    Download: Download,
    Eye: Eye,
    GripVertical: GripVertical,
    Send: Send,
    Star: Star,
    More: MoreVertical,
};
