import {
    LuArrowRightLeft,
    LuBell,
    LuBook,
    LuBuilding,
    LuCheck,
    LuChevronDown,
    LuChevronRight,
    LuChevronsUpDown,
    LuCreditCard,
    LuDatabase,
    LuDownload,
    LuEye,
    LuFileText,
    LuFileUp,
    LuLayoutDashboard,
    LuLock,
    LuLogOut,
    LuMail,
    LuMapPin,
    LuMenu,
    LuMessageSquare,
    LuNotebook,
    LuPencil,
    LuPhone,
    LuPlus,
    LuReceipt,
    LuSave,
    LuSearch,
    LuSend,
    LuSettings,
    LuShield,
    LuTrash2,
    LuUser,
    LuUsers,
    LuX,
} from 'react-icons/lu';

export const Icons = {
    Dashboard: LuLayoutDashboard,
    Transactions: LuArrowRightLeft,
    Reports: LuFileText,
    ChartOfAccounts: LuBook,
    JournalEntries: LuNotebook,
    Invoices: LuFileText, // Or LuFileSpreadsheet if preferred
    Expenses: LuReceipt,
    Documents: LuFileUp,
    ClientReview: LuMessageSquare,
    Settings: LuSettings,
    Profile: LuUser, // or LuUserCircle
    Billing: LuCreditCard,
    Notifications: LuBell,
    Logout: LuLogOut,
    ChevronRight: LuChevronRight,
    ChevronDown: LuChevronDown,
    ChevronsUpDown: LuChevronsUpDown,
    UserCircle: LuUser, // Fallback to LuUser if LuUserCircle/LuCircleUser is not available or just use LuUser
    Menu: LuMenu,
    Search: LuSearch,
    Building: LuBuilding,
    Users: LuUsers,
    Shield: LuShield,
    Lock: LuLock,
    Database: LuDatabase,
    Edit: LuPencil,
    Save: LuSave,
    Plus: LuPlus,
    Trash: LuTrash2,
    Mail: LuMail,
    Phone: LuPhone,
    MapPin: LuMapPin,
    Check: LuCheck,
    Close: LuX,
    Download: LuDownload,
    Eye: LuEye,
    Send: LuSend,
};
