import {
    LuArrowRightLeft,
    LuBell,
    LuBook,
    LuBuilding,
    LuChevronDown,
    LuChevronRight,
    LuChevronsUpDown,
    LuCreditCard,
    LuDatabase,
    LuFileText,
    LuFileUp,
    LuLayoutDashboard,
    LuLock,
    LuLogOut,
    LuMenu,
    LuMessageSquare,
    LuNotebook,
    LuReceipt,
    LuSearch,
    LuSettings,
    LuShield,
    LuUser,
    LuUsers,
} from 'react-icons/lu';

export const Icons = {
    Dashboard: LuLayoutDashboard,
    Transactions: LuArrowRightLeft,
    Reports: LuFileText,
    ChartOfAccounts: LuBook,
    JournalEntries: LuNotebook,
    Invoices: LuFileText, // Or LuFileSpreadsheet if preferred
    Expenses: LuReceipt,
    Documents: LuFileUp,
    ClientReview: LuMessageSquare,
    Settings: LuSettings,
    Profile: LuUser, // or LuUserCircle
    Billing: LuCreditCard,
    Notifications: LuBell,
    Logout: LuLogOut,
    ChevronRight: LuChevronRight,
    ChevronDown: LuChevronDown,
    ChevronsUpDown: LuChevronsUpDown,
    UserCircle: LuUser, // Fallback to LuUser if LuUserCircle/LuCircleUser is not available or just use LuUser
    Menu: LuMenu,
    Search: LuSearch,
    Building: LuBuilding,
    Users: LuUsers,
    Shield: LuShield,
    Lock: LuLock,
    Database: LuDatabase,
};
